export const __esModule: true;
export const container: string;
export const heading: string;
export const cardContainer: string;
export const warning: string;
export const downloaded: string;
export const download: string;
export const done: string;
export const close: string;
