export const __esModule: true;
export const buttonPrimary: string;
export const buttonSecondary: string;
export const buttonWide: string;
export const buttonIcon: string;
export const circle: string;
export const buttonCheckmark: string;
export const buttonCross: string;
export const buttonsLine: string;
