export const __esModule: true;
export const container: string;
export const heading: string;
export const subline: string;
export const explanation: string;
export const functionality: string;
export const avatar: string;
export const deposit: string;
export const upgrade: string;
