export const __esModule: true;
export const container: string;
export const heading: string;
export const subline: string;
export const endpointLine: string;
export const endpoint: string;
export const save: string;
export const cancel: string;
export const reset: string;
