export const __esModule: true;
export const container: string;
export const heading: string;
export const subline: string;
export const warning: string;
export const credentials: string;
export const buttonsLine: string;
export const cancel: string;
export const cta: string;
