export const __esModule: true;
export const container: string;
export const heading: string;
export const subline: string;
export const link: string;
export const didLine: string;
export const endpoints: string;
export const web3Name: string;
export const downgrade: string;
