export const __esModule: true;
export const resetLine: string;
export const reset: string;
export const passwordLabel: string;
export const passwordLine: string;
export const password: string;
export const errorTooltip: string;
export const rememberLabel: string;
export const remember: string;
