export const __esModule: true;
export const overlay: string;
export const heading: string;
export const explanation: string;
export const cta: string;
export const listHeading: string;
export const list: string;
export const legacyIdentity: string;
export const close: string;
