name: Packages the public version
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VARIANT: public
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.4.0

      - name: Configure Node and package manager
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build code
        run: yarn build

      - name: Package extension
        run: yarn package

      - name: Rename artifact as public
        run: cd dist/web-ext-artifacts/ && mv * $(ls | sed 's/-/-public-/')

      - name: Publish on GitHub
        uses: actions/upload-artifact@v2
        with:
          name: sporran-extension-${{ github.sha }}
          path: dist/web-ext-artifacts/*
