name: Packages the public version
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VARIANT: public
    steps:
      - name: Configure Node and package manager
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Checkout the code
        uses: actions/checkout@v2.3.4

      - name: Get package manager cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Package manager cache
        id: yarn-cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build code
        run: yarn build

      - name: Package extension
        run: yarn package

      - name: Publish on GitHub
        uses: actions/upload-artifact@v2
        with:
          name: sporran-extension-${{ github.sha }}
          path: dist/web-ext-artifacts/sporran-1.0.0.zip
